# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Resume"
license = "MIT"
licenselink = "https://github.com/eddiewebb/hugo-resume/blob/master/LICENSE.md"
description = "Personal resume with social handles, skills inventory, work history and portfolio. Ported from StartBootstrap 'Resume' theme"
homepage = "https://edwardwebb.com/"
tags = ["portfolio","resume","responsive"]
features = ["social","mobile","projects","responsive","qr-code"]
min_version = "0.1"

[author]
  name = "Eddie Webb"
  homepage = "https://edwardawebb.com"


# If porting an existing theme
[original]
  name = "Start Bootstrap Resume"
  homepage = "https://startbootstrap.com/template-overviews/resume/"
  repo = "https://github.com/BlackrockDigital/startbootstrap-resume"
